// This file is @generated by prost-build.
/// タイムゾーン保持可能な日時メッセージです。
#[derive(serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Instant {
    /// 1970/1/1 00:00:00からの秒数
    #[prost(int64, tag = "1")]
    pub seconds: i64,
    /// 秒未満のナノ秒
    #[prost(uint32, tag = "2")]
    pub nanos: u32,
    /// タイムゾーンオフセット（秒単位）
    #[prost(int32, tag = "3")]
    pub timezone_offset: i32,
}
